library(readr)
binary.1 <- read_delim("20706.PTmergedrows.binary", "\t", escape_double = FALSE, col_types = cols(CHROM = col_character(), POS = col_character()), trim_ws = TRUE)
Phase.1 <- read_delim("h0.7875.s320.LG.txt", "\t", escape_double = FALSE, col_types = cols(CHR = col_character(), POS = col_character()), trim_ws = TRUE)
binary.1<-data.frame(binary.1)
Phase.1<-data.frame(Phase.1)
binary.1$ID<-paste(binary.1$CHROM,sep="_")
Phase.1$ID<-paste(Phase.1$CHR,sep="_")
write.table(binary.1[,1:ncol(binary.1)],file=paste("ID.binary",sep=""),quote=F,sep="\t",row.names=F)
write.table(Phase.1[,1:ncol(Phase.1)],file=paste("ID.LGS.txt",sep=""),quote=F,sep="\t",row.names=F)
binary.2 <- read_delim("20706.PT.parents.GQ10.shared.binary", "\t", escape_double = FALSE, col_types = cols(CHROM = col_character(), POS = col_character()), trim_ws = TRUE)
binary.2<-data.frame(binary.2)
binary.2$ID<-paste(binary.2$CHROM,sep="_")
write.table(binary.2[,1:ncol(binary.2)],file=paste("parental.binary",sep=""),quote=F,sep="\t",row.names=F)
