library(readr)
binary.1 <- read_delim("newkid.binary", "\t", escape_double = FALSE, col_types = cols(CHROM = col_character(), POS = col_character()), trim_ws = TRUE)
Phase.1 <- read_delim("phased.txt", "\t", escape_double = FALSE, col_types = cols(CHR = col_character(), POS = col_character()), trim_ws = TRUE)
binary.1<-data.frame(binary.1)
Phase.1<-data.frame(Phase.1)
binary.1$ID<-paste(binary.1$CHROM,binary.1$POS,sep="_")
Phase.1$ID<-paste(Phase.1$CHR,Phase.1$POS,sep="_")
write.table(binary.1[,1:ncol(binary.1)],file=paste("ID.binary",sep=""),quote=F,sep="\t",row.names=F)
write.table(Phase.1[,1:ncol(Phase.1)],file=paste("IDphased.txt",sep=""),quote=F,sep="\t",row.names=F)

binary.2 <- read_delim("binary1.2.binary", "\t", escape_double = FALSE, col_types = cols(CHROM = col_character(), POS = col_character()), trim_ws = TRUE)
Phase.1 <- read_delim("phased1.2.txt", "\t", escape_double = FALSE, col_types = cols(CHR = col_character(), POS = col_character()), trim_ws = TRUE)
binary.2<-data.frame(binary.2)
Phase.2<-data.frame(Phase.2)
binary.2$ID<-paste(binary.2$CHROM,binary.2$POS,sep="_")
Phase.2$ID<-paste(Phase.2$CHR,Phase.2$POS,sep="_")
write.table(binary.2[,1:ncol(binary.1)],file=paste("N1.2.binary",sep=""),quote=F,sep="\t",row.names=F)
write.table(Phase.2[,1:ncol(Phase.1)],file=paste("phasedN1.2.txt",sep=""),quote=F,sep="\t",row.names=F)